---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-kafka
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 10G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-zk
provisioner: openebs.io/provisioner-iscsi
parameters:
  pool: hostdir-var
  replica: "2"
  size: 5G
---