---
- name: Delete the iSCSI target 
  shell: source ~/.profile; kubectl delete -f {{ volume_def }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm the iSCSI target has been deleted
  shell: source ~/.profile; kubectl get pvc
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' not in result.stdout"
  delay: 120 
  retries: 6


   
